### ISSUE TITLE
support for mapbox jl gs 

### ISSUE THREAD

**Issue by w-e-b-h-u-n-t-e-r** [bewithjonam/mapboxgl-spiderifier#13]
How to add to markers layer ?  
------
map.addLayer({
        id: 'unclustered-point',
        type: 'circle',
        source: 'ware',
        filter: ['!', ['has', 'point_count']],
        paint: {
            'circle-color': '#4bb4f5',
            'circle-radius': 6,
            'circle-stroke-width': 2,
            'circle-stroke-color': '#fff'
        }
    });
-------

**Comment by bewithjonam** [comment]
@eudruz, I cannot understand your requirement fully. 

Refer to example, example-mapbox-gl-cluster-spiderfy . It has circles for clusters and symbols for individual pins.

Examples: https://bewithjonam.github.io/mapboxgl-spiderifier/docs/index.html 

https://github.com/bewithjonam/mapboxgl-spiderifier/blob/master/docs/example-mapbox-gl-cluster-spiderfy.html

Hope this helps.

**Comment by bewithjonam** [comment]
Closed due inactivity
