### ISSUE TITLE
problem with spiderifier code on Mapbox.

### ISSUE THREAD

**Issue by lixiao321** [bewithjonam/mapboxgl-spiderifier#14]
Hi, I followed the code but it doesn't work. The map does not show up. I get the code here: https://github.com/bewithjonam/mapboxgl-spiderifier/blob/master/docs/example-mapbox-gl-cluster-spiderfy.html 

Would you be kind enough to help me identify what's wrong here? 
https://glitch.com/edit/#!/emphasized-atom-clover?path=index.html%3A85%3A33

This is a cluster map I made: https://glittery-unexpected-comic.glitch.me 
I want to add spiderifier with popup box. 

Thank you very much!

**Comment by bewithjonam** [comment]
Which version of mapbox-gl-js are you using. What error are you getting? 

The examples demonstrate all the different options in this library. You can find all the working examples here:
https://bewithjonam.github.io/mapboxgl-spiderifier/docs/index.html (All examples list)
https://bewithjonam.github.io/mapboxgl-spiderifier/docs/example-mapbox-gl-cluster-spiderfy.html

**Comment by lixiao321** [comment]
I am using the latest mapbox-gl-js. I saw your examples. I made a cluster map with spider legs (that's your example 3). My problem now is to add popup box to spider legs (like your example 2) in the cluster map. My map wants to be the combination of your example 2 and 3. However, I added the code you gave on example 2, "the customize pin popups", https://github.com/bewithjonam/mapboxgl-spiderifier , the spider leg simple disappears and no popup box either. The problem seems to be this area: 

initializeLeg: function(spiderLeg) {
      var $spiderPinCustom = $('<div>', {class: 'spider-point-circle'});


This is my code. Would you be kind enough to help me what's going wrong with the customize pin popups here? From line 404 and below. The codes above this line work well. 
https://github.com/lixiao321/spider-leg-map/blob/main/leg%20without%20popup

Thank you very much!

**Comment by bewithjonam** [comment]
Please check this doc sample. https://github.com/bewithjonam/mapboxgl-spiderifier#custom-pins-with-popup

You need to use the `initializeLeg` option while creating spiderfier and give setup popups on hover.  In case of filing issues, please provide a reproable jsfiddle or something like that for quick reference. The html file you attached has errors.

I am closing this issue. Not sure, if I will be able to help like this in future.  Will make the enhance the docs better in a couple of days.

Fix for the html that you gave. https://gist.github.com/bewithjonam/68e2fb92d692b110e96e12c9dccb9fbe

Changes mentioned below.

```
<script
      src="https://code.jquery.com/jquery-3.5.1.min.js"
      integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
      crossorigin="anonymous"></script>
```

```
      var map = new mapboxgl.Map({
        container: "map",
        style: "mapbox://styles/mapbox/dark-v10",
        center: [40.876, 34.577],
        zoom: 5.81
      });

      spiderifier = new MapboxglSpiderifier(map, {
        customPin: true,
        initializeLeg: function(spiderLeg) {
          var popup = new mapboxgl.Popup({
            closeButton: true,
            closeOnClick: false,
            offset: MapboxglSpiderifier.popupOffsetForSpiderLeg(spiderLeg)
          });

          popup.setHTML(spiderLeg.feature.description);
          spiderLeg.mapboxMarker.setPopup(popup);

          $(spiderLeg.elements.container)
            .on('mouseenter', function(){
              popup.addTo(map);
            map.getCanvas().style.cursor = "pointer";
            })
            .on('mouseleave', function(){
            map.getCanvas().style.cursor = "";
              popup.remove();
          });
        }
      });
```
