### ISSUE TITLE
Multiple Spiderifier Instances

### ISSUE THREAD

**Issue by enersis-pst** [bewithjonam/mapboxgl-spiderifier#15]
Hello,
would it be possible to create more then one instance to open multi spiderifier at the same time?
if i create more then one only the last would be opend and the other are closed. Maybe because `previousSpiderLegs` is a global variable?

**Comment by bewithjonam** [comment]
It has been already fixed but was not released in npm.
I just pushed a new version `1.0.10` with all recent lint fixes (which covers global vars).

**Comment by bewithjonam** [comment]
Closing issue

**Comment by enersis-pst** [comment]
thanks

**Comment by enersis-pst** [comment]
where i will find this version?
is there also a npm package?
