### ISSUE TITLE
Left offset marker from cluster point

### ISSUE THREAD

**Issue by joanthethings** [bewithjonam/mapboxgl-spiderifier#16]
Hello! I have little bug hope you can help me :)

![image](https://user-images.githubusercontent.com/79305731/130417370-2f152352-794c-4282-a1c2-a46186600cee.png)

My code is here:

//Spiderfy feature
      vm.spiderifier = new MapboxglSpiderifier(vm.map, {
        customPin: true,
        //No differnece on animate
        animate: true,
        animationSpeed: 200,
        initializeLeg: initializeSpiderLeg
      })
      vm.SPIDERFY_FROM_ZOOM = 18
    }

    function initializeSpiderLeg(spiderLeg) {
      var pinElem = spiderLeg.elements.pin;
      var feature = spiderLeg.feature;
      var popup;

      pinElem.className = pinElem.className + 'fa-stack fa-lg';
      pinElem.innerHTML = '<img src=https://assets.mapquestapi.com/icon/v2/marker-' + chooseColor(feature.icon) + '-FFFFFF' + '.png>'

      //Centra millor leafes i fer que el popup surti fent el onClick
      $(pinElem)
        .on('mouseenter', function () {
          popup = new mapboxgl.Popup({
            closeButton: true,
            closeOnClick: false,
            offset: MapboxglSpiderifier.popupOffsetForSpiderLeg(spiderLeg)
          });

          popup.setHTML(feature.description)
            .addTo(vm.map)

          spiderLeg.mapboxMarker.setPopup(popup);
        })
        .on('mouseleave', function () {
          if (popup) {
            popup.remove();
          }
        });
    }

**Comment by bewithjonam** [comment]
Lets say the location for the marker is 100px, 100px. When you add an image to the marker, you want the bottom center of the image (pointed side) to be at 100px, 100px. But what happens is, the image's top left corner gets placed at 100px,100px. 

So it feels like it is positioned wrongly. Based on the size of your image, add margins as done in this example.

https://github.com/bewithjonam/mapboxgl-spiderifier#custom-pins-with-popup

**Comment by joanthethings** [comment]
Thanks, fixed playing with margins!
