### ISSUE TITLE
@types module

### ISSUE THREAD

**Issue by lancegliser** [bewithjonam/mapboxgl-spiderifier#22]
Hey @bewithjonam, I appreciate the work you've done here.  Rigged up a typing package to publish in support.
I've listed you as an owner so have rights to maintain if you want. That might result in some notifications you'd prefer to skip though. Please let me know if you'd like me to keep or maintain you in that status!

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67917

**Comment by bewithjonam** [comment]
Looks good... 👍
