### ISSUE TITLE
Cant open the popup with 'click' instead of 'mouseenter'

### ISSUE THREAD

**Issue by Sionicmon** [bewithjonam/mapboxgl-spiderifier#6]
Hi,

i want to open the popup on 'click' not on 'mouseenter', but if i change it to 'click' it doesnt work.
Can you say me how i can open it with 'click'?

`$(pinElem)
          .on('click', function(){

              popup = new mapboxgl.Popup({
                closeButton: true,
                closeOnClick: true,
                offset: MapboxglSpiderifier.popupOffsetForSpiderLeg(spiderLeg)
              });

              popup.setHTML('<div> ... </div>')
                .addTo(map)
              spiderLeg.mapboxMarker.setPopup(popup);

          })
          .on('mouseleave', function(){
            if(popup){
              popup.remove();
            }
          });`

**Comment by Sionicmon** [comment]
Okay i solved it by adding
`e.stopPropagation();`
after the .setPopup(popup).

**Comment by bewithjonam** [comment]
I was out on vacation. Just checked this. Good that you were able to get it working.
