### ISSUE TITLE
how to use this awesome lib with angular

### ISSUE THREAD

**Issue by modyz** [bewithjonam/mapboxgl-spiderifier#7]
i am really finding difficulty adding this lib to angular can you please show us how ?!

**Comment by bewithjonam** [comment]
http://jsfiddle.net/bewithjonam/p4cuswb5/

**Comment by stolotti** [comment]
Hi, the example works with AngularJS (AKA angular 1)
It doesn't work in Angular 2 to 7

**Comment by ashishkaul05** [comment]
Hi, is there any example available now for angular latest version?
